# Generated by Django 5.0.4 on 2024-04-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref', models.CharField(max_length=100)),
                ('license_key', models.CharField(max_length=100, unique=True)),
                ('expiry_date', models.DateField()),
                ('is_valid_lifetime', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('activation_date', models.DateTimeField(blank=True, null=True)),
                ('encrypted_config', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
