# Generated by Django 5.0.4 on 2024-04-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='activation_date',
            field=models.DateTimeField(blank=True, help_text='Activation date of the license. Required when updating a license.', null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='encrypted_config',
            field=models.TextField(blank=True, help_text='Encrypted configuration data. Required when updating a license.', null=True),
        ),
    ]
