# Generated by Django 5.0.4 on 2024-04-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0003_license_email_alter_license_activation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
