# Generated by Django 5.0.4 on 2024-04-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0004_alter_license_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
