# Generated by Django 5.0.4 on 2024-04-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0006_alter_license_license_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='encrypted_config',
        ),
    ]
