# Generated by Django 5.0.4 on 2024-04-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0007_remove_license_encrypted_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='mac_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
