# Generated by Django 5.0.4 on 2024-04-12 06:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0009_software_remove_license_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
