# Generated by Django 5.0.4 on 2024-04-12 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0010_alter_software_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Software',
        ),
    ]
