# Generated by Django 5.0.4 on 2024-04-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0011_delete_software'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='ids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
