# Generated by Django 5.0.4 on 2024-04-14 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0012_license_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='ids',
            field=models.TextField(blank=True, help_text='Must be comma separated', null=True),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('un', models.CharField(max_length=200)),
                ('pw', models.CharField(max_length=200)),
                ('la', models.DateTimeField(auto_now_add=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_ids', to='license.license')),
            ],
        ),
    ]
