# Generated by Django 5.0.4 on 2024-04-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0013_alter_license_ids_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='la',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
